apiVersion: apps/v1
kind: Deployment
metadata:
  name: 'virtual-trainer'
  labels:
    app: 'virtual-trainer'
    environment: 'development'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: 'virtual-trainer'
  template:
    metadata:
      labels:
        app: 'virtual-trainer'
        environment: 'development'
    spec:
      containers:
        - name: 'virtual-trainer'
          image: 'gcr.io/kubernetsalura/virtual-trainer/master:latest'
          imagePullPolicy: Always
          ports:
            - containerPort: 8085
---

apiVersion: v1
kind: Service
metadata:
  name: 'virtual-trainer'
spec:
  type: ClusterIP
  selector:
    app: 'virtual-trainer'
  ports:
  - name: http
    port: 8085
    targetPort: 8085
    
---

apiVersion: v1
kind: Service
metadata:
  name: 'virtual-trainer-external'
spec:
  type: LoadBalancer
  selector:
    app: 'virtual-trainer'
  ports:
  - name: http
    port: 8085
    targetPort: 8085
            